version: '3.1'

services:
  rnv-de-api-mysql-service:
    image: mysql:5.7
    ports:
      - '3306:3306'
    container_name: rnv-de-api-mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: this_is_pw
      MYSQL_DATABASE: rnv-api
      MYSQL_USER: rnv-api
      MYSQL_PASSWORD: this_is_pw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
